// Code generated by ent, DO NOT EDIT.

package cardmailboxcredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the cardmailboxcredential type in the database.
	Label = "card_mailbox_credential"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldMailboxURL holds the string denoting the mailbox_url field in the database.
	FieldMailboxURL = "mailbox_url"
	// FieldLastCode holds the string denoting the last_code field in the database.
	FieldLastCode = "last_code"
	// FieldLastStatus holds the string denoting the last_status field in the database.
	FieldLastStatus = "last_status"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldLastFetchedAt holds the string denoting the last_fetched_at field in the database.
	FieldLastFetchedAt = "last_fetched_at"
	// Table holds the table name of the cardmailboxcredential in the database.
	Table = "card_mailbox_credentials"
)

// Columns holds all SQL columns for cardmailboxcredential fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldEmail,
	FieldMailboxURL,
	FieldLastCode,
	FieldLastStatus,
	FieldLastError,
	FieldLastFetchedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// MailboxURLValidator is a validator for the "mailbox_url" field. It is called by the builders before save.
	MailboxURLValidator func(string) error
	// LastCodeValidator is a validator for the "last_code" field. It is called by the builders before save.
	LastCodeValidator func(string) error
	// LastStatusValidator is a validator for the "last_status" field. It is called by the builders before save.
	LastStatusValidator func(string) error
)

// OrderOption defines the ordering options for the CardMailboxCredential queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByMailboxURL orders the results by the mailbox_url field.
func ByMailboxURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMailboxURL, opts...).ToFunc()
}

// ByLastCode orders the results by the last_code field.
func ByLastCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCode, opts...).ToFunc()
}

// ByLastStatus orders the results by the last_status field.
func ByLastStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastStatus, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByLastFetchedAt orders the results by the last_fetched_at field.
func ByLastFetchedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastFetchedAt, opts...).ToFunc()
}
