// Code generated by ent, DO NOT EDIT.

package cardmailboxcredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldEmail, v))
}

// MailboxURL applies equality check predicate on the "mailbox_url" field. It's identical to MailboxURLEQ.
func MailboxURL(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldMailboxURL, v))
}

// LastCode applies equality check predicate on the "last_code" field. It's identical to LastCodeEQ.
func LastCode(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldLastCode, v))
}

// LastStatus applies equality check predicate on the "last_status" field. It's identical to LastStatusEQ.
func LastStatus(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldLastStatus, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldLastError, v))
}

// LastFetchedAt applies equality check predicate on the "last_fetched_at" field. It's identical to LastFetchedAtEQ.
func LastFetchedAt(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldLastFetchedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLTE(FieldUpdatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldContainsFold(FieldEmail, v))
}

// MailboxURLEQ applies the EQ predicate on the "mailbox_url" field.
func MailboxURLEQ(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldMailboxURL, v))
}

// MailboxURLNEQ applies the NEQ predicate on the "mailbox_url" field.
func MailboxURLNEQ(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNEQ(FieldMailboxURL, v))
}

// MailboxURLIn applies the In predicate on the "mailbox_url" field.
func MailboxURLIn(vs ...string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldIn(FieldMailboxURL, vs...))
}

// MailboxURLNotIn applies the NotIn predicate on the "mailbox_url" field.
func MailboxURLNotIn(vs ...string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNotIn(FieldMailboxURL, vs...))
}

// MailboxURLGT applies the GT predicate on the "mailbox_url" field.
func MailboxURLGT(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGT(FieldMailboxURL, v))
}

// MailboxURLGTE applies the GTE predicate on the "mailbox_url" field.
func MailboxURLGTE(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGTE(FieldMailboxURL, v))
}

// MailboxURLLT applies the LT predicate on the "mailbox_url" field.
func MailboxURLLT(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLT(FieldMailboxURL, v))
}

// MailboxURLLTE applies the LTE predicate on the "mailbox_url" field.
func MailboxURLLTE(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLTE(FieldMailboxURL, v))
}

// MailboxURLContains applies the Contains predicate on the "mailbox_url" field.
func MailboxURLContains(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldContains(FieldMailboxURL, v))
}

// MailboxURLHasPrefix applies the HasPrefix predicate on the "mailbox_url" field.
func MailboxURLHasPrefix(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldHasPrefix(FieldMailboxURL, v))
}

// MailboxURLHasSuffix applies the HasSuffix predicate on the "mailbox_url" field.
func MailboxURLHasSuffix(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldHasSuffix(FieldMailboxURL, v))
}

// MailboxURLEqualFold applies the EqualFold predicate on the "mailbox_url" field.
func MailboxURLEqualFold(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEqualFold(FieldMailboxURL, v))
}

// MailboxURLContainsFold applies the ContainsFold predicate on the "mailbox_url" field.
func MailboxURLContainsFold(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldContainsFold(FieldMailboxURL, v))
}

// LastCodeEQ applies the EQ predicate on the "last_code" field.
func LastCodeEQ(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldLastCode, v))
}

// LastCodeNEQ applies the NEQ predicate on the "last_code" field.
func LastCodeNEQ(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNEQ(FieldLastCode, v))
}

// LastCodeIn applies the In predicate on the "last_code" field.
func LastCodeIn(vs ...string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldIn(FieldLastCode, vs...))
}

// LastCodeNotIn applies the NotIn predicate on the "last_code" field.
func LastCodeNotIn(vs ...string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNotIn(FieldLastCode, vs...))
}

// LastCodeGT applies the GT predicate on the "last_code" field.
func LastCodeGT(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGT(FieldLastCode, v))
}

// LastCodeGTE applies the GTE predicate on the "last_code" field.
func LastCodeGTE(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGTE(FieldLastCode, v))
}

// LastCodeLT applies the LT predicate on the "last_code" field.
func LastCodeLT(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLT(FieldLastCode, v))
}

// LastCodeLTE applies the LTE predicate on the "last_code" field.
func LastCodeLTE(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLTE(FieldLastCode, v))
}

// LastCodeContains applies the Contains predicate on the "last_code" field.
func LastCodeContains(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldContains(FieldLastCode, v))
}

// LastCodeHasPrefix applies the HasPrefix predicate on the "last_code" field.
func LastCodeHasPrefix(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldHasPrefix(FieldLastCode, v))
}

// LastCodeHasSuffix applies the HasSuffix predicate on the "last_code" field.
func LastCodeHasSuffix(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldHasSuffix(FieldLastCode, v))
}

// LastCodeIsNil applies the IsNil predicate on the "last_code" field.
func LastCodeIsNil() predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldIsNull(FieldLastCode))
}

// LastCodeNotNil applies the NotNil predicate on the "last_code" field.
func LastCodeNotNil() predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNotNull(FieldLastCode))
}

// LastCodeEqualFold applies the EqualFold predicate on the "last_code" field.
func LastCodeEqualFold(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEqualFold(FieldLastCode, v))
}

// LastCodeContainsFold applies the ContainsFold predicate on the "last_code" field.
func LastCodeContainsFold(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldContainsFold(FieldLastCode, v))
}

// LastStatusEQ applies the EQ predicate on the "last_status" field.
func LastStatusEQ(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldLastStatus, v))
}

// LastStatusNEQ applies the NEQ predicate on the "last_status" field.
func LastStatusNEQ(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNEQ(FieldLastStatus, v))
}

// LastStatusIn applies the In predicate on the "last_status" field.
func LastStatusIn(vs ...string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldIn(FieldLastStatus, vs...))
}

// LastStatusNotIn applies the NotIn predicate on the "last_status" field.
func LastStatusNotIn(vs ...string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNotIn(FieldLastStatus, vs...))
}

// LastStatusGT applies the GT predicate on the "last_status" field.
func LastStatusGT(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGT(FieldLastStatus, v))
}

// LastStatusGTE applies the GTE predicate on the "last_status" field.
func LastStatusGTE(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGTE(FieldLastStatus, v))
}

// LastStatusLT applies the LT predicate on the "last_status" field.
func LastStatusLT(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLT(FieldLastStatus, v))
}

// LastStatusLTE applies the LTE predicate on the "last_status" field.
func LastStatusLTE(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLTE(FieldLastStatus, v))
}

// LastStatusContains applies the Contains predicate on the "last_status" field.
func LastStatusContains(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldContains(FieldLastStatus, v))
}

// LastStatusHasPrefix applies the HasPrefix predicate on the "last_status" field.
func LastStatusHasPrefix(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldHasPrefix(FieldLastStatus, v))
}

// LastStatusHasSuffix applies the HasSuffix predicate on the "last_status" field.
func LastStatusHasSuffix(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldHasSuffix(FieldLastStatus, v))
}

// LastStatusIsNil applies the IsNil predicate on the "last_status" field.
func LastStatusIsNil() predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldIsNull(FieldLastStatus))
}

// LastStatusNotNil applies the NotNil predicate on the "last_status" field.
func LastStatusNotNil() predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNotNull(FieldLastStatus))
}

// LastStatusEqualFold applies the EqualFold predicate on the "last_status" field.
func LastStatusEqualFold(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEqualFold(FieldLastStatus, v))
}

// LastStatusContainsFold applies the ContainsFold predicate on the "last_status" field.
func LastStatusContainsFold(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldContainsFold(FieldLastStatus, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldContainsFold(FieldLastError, v))
}

// LastFetchedAtEQ applies the EQ predicate on the "last_fetched_at" field.
func LastFetchedAtEQ(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldEQ(FieldLastFetchedAt, v))
}

// LastFetchedAtNEQ applies the NEQ predicate on the "last_fetched_at" field.
func LastFetchedAtNEQ(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNEQ(FieldLastFetchedAt, v))
}

// LastFetchedAtIn applies the In predicate on the "last_fetched_at" field.
func LastFetchedAtIn(vs ...time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldIn(FieldLastFetchedAt, vs...))
}

// LastFetchedAtNotIn applies the NotIn predicate on the "last_fetched_at" field.
func LastFetchedAtNotIn(vs ...time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNotIn(FieldLastFetchedAt, vs...))
}

// LastFetchedAtGT applies the GT predicate on the "last_fetched_at" field.
func LastFetchedAtGT(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGT(FieldLastFetchedAt, v))
}

// LastFetchedAtGTE applies the GTE predicate on the "last_fetched_at" field.
func LastFetchedAtGTE(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldGTE(FieldLastFetchedAt, v))
}

// LastFetchedAtLT applies the LT predicate on the "last_fetched_at" field.
func LastFetchedAtLT(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLT(FieldLastFetchedAt, v))
}

// LastFetchedAtLTE applies the LTE predicate on the "last_fetched_at" field.
func LastFetchedAtLTE(v time.Time) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldLTE(FieldLastFetchedAt, v))
}

// LastFetchedAtIsNil applies the IsNil predicate on the "last_fetched_at" field.
func LastFetchedAtIsNil() predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldIsNull(FieldLastFetchedAt))
}

// LastFetchedAtNotNil applies the NotNil predicate on the "last_fetched_at" field.
func LastFetchedAtNotNil() predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.FieldNotNull(FieldLastFetchedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CardMailboxCredential) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CardMailboxCredential) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CardMailboxCredential) predicate.CardMailboxCredential {
	return predicate.CardMailboxCredential(sql.NotPredicates(p))
}
