// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cardmailboxcredential"
)

// CardMailboxCredentialCreate is the builder for creating a CardMailboxCredential entity.
type CardMailboxCredentialCreate struct {
	config
	mutation *CardMailboxCredentialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CardMailboxCredentialCreate) SetCreatedAt(v time.Time) *CardMailboxCredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CardMailboxCredentialCreate) SetNillableCreatedAt(v *time.Time) *CardMailboxCredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CardMailboxCredentialCreate) SetUpdatedAt(v time.Time) *CardMailboxCredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CardMailboxCredentialCreate) SetNillableUpdatedAt(v *time.Time) *CardMailboxCredentialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *CardMailboxCredentialCreate) SetEmail(v string) *CardMailboxCredentialCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetMailboxURL sets the "mailbox_url" field.
func (_c *CardMailboxCredentialCreate) SetMailboxURL(v string) *CardMailboxCredentialCreate {
	_c.mutation.SetMailboxURL(v)
	return _c
}

// SetRawJSON sets the "raw_json" field.
func (_c *CardMailboxCredentialCreate) SetRawJSON(v string) *CardMailboxCredentialCreate {
	_c.mutation.SetRawJSON(v)
	return _c
}

// SetLastCode sets the "last_code" field.
func (_c *CardMailboxCredentialCreate) SetLastCode(v string) *CardMailboxCredentialCreate {
	_c.mutation.SetLastCode(v)
	return _c
}

// SetNillableLastCode sets the "last_code" field if the given value is not nil.
func (_c *CardMailboxCredentialCreate) SetNillableLastCode(v *string) *CardMailboxCredentialCreate {
	if v != nil {
		_c.SetLastCode(*v)
	}
	return _c
}

// SetLastStatus sets the "last_status" field.
func (_c *CardMailboxCredentialCreate) SetLastStatus(v string) *CardMailboxCredentialCreate {
	_c.mutation.SetLastStatus(v)
	return _c
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_c *CardMailboxCredentialCreate) SetNillableLastStatus(v *string) *CardMailboxCredentialCreate {
	if v != nil {
		_c.SetLastStatus(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *CardMailboxCredentialCreate) SetLastError(v string) *CardMailboxCredentialCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *CardMailboxCredentialCreate) SetNillableLastError(v *string) *CardMailboxCredentialCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (_c *CardMailboxCredentialCreate) SetLastFetchedAt(v time.Time) *CardMailboxCredentialCreate {
	_c.mutation.SetLastFetchedAt(v)
	return _c
}

// SetNillableLastFetchedAt sets the "last_fetched_at" field if the given value is not nil.
func (_c *CardMailboxCredentialCreate) SetNillableLastFetchedAt(v *time.Time) *CardMailboxCredentialCreate {
	if v != nil {
		_c.SetLastFetchedAt(*v)
	}
	return _c
}

// Mutation returns the CardMailboxCredentialMutation object of the builder.
func (_c *CardMailboxCredentialCreate) Mutation() *CardMailboxCredentialMutation {
	return _c.mutation
}

// Save creates the CardMailboxCredential in the database.
func (_c *CardMailboxCredentialCreate) Save(ctx context.Context) (*CardMailboxCredential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CardMailboxCredentialCreate) SaveX(ctx context.Context) *CardMailboxCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CardMailboxCredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CardMailboxCredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CardMailboxCredentialCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cardmailboxcredential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := cardmailboxcredential.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CardMailboxCredentialCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CardMailboxCredential.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CardMailboxCredential.updated_at"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "CardMailboxCredential.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := cardmailboxcredential.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MailboxURL(); !ok {
		return &ValidationError{Name: "mailbox_url", err: errors.New(`ent: missing required field "CardMailboxCredential.mailbox_url"`)}
	}
	if v, ok := _c.mutation.MailboxURL(); ok {
		if err := cardmailboxcredential.MailboxURLValidator(v); err != nil {
			return &ValidationError{Name: "mailbox_url", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.mailbox_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RawJSON(); !ok {
		return &ValidationError{Name: "raw_json", err: errors.New(`ent: missing required field "CardMailboxCredential.raw_json"`)}
	}
	if v, ok := _c.mutation.RawJSON(); ok {
		if err := cardmailboxcredential.RawJSONValidator(v); err != nil {
			return &ValidationError{Name: "raw_json", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.raw_json": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastCode(); ok {
		if err := cardmailboxcredential.LastCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_code", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.last_code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastStatus(); ok {
		if err := cardmailboxcredential.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.last_status": %w`, err)}
		}
	}
	return nil
}

func (_c *CardMailboxCredentialCreate) sqlSave(ctx context.Context) (*CardMailboxCredential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CardMailboxCredentialCreate) createSpec() (*CardMailboxCredential, *sqlgraph.CreateSpec) {
	var (
		_node = &CardMailboxCredential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cardmailboxcredential.Table, sqlgraph.NewFieldSpec(cardmailboxcredential.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cardmailboxcredential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(cardmailboxcredential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(cardmailboxcredential.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.MailboxURL(); ok {
		_spec.SetField(cardmailboxcredential.FieldMailboxURL, field.TypeString, value)
		_node.MailboxURL = value
	}
	if value, ok := _c.mutation.RawJSON(); ok {
		_spec.SetField(cardmailboxcredential.FieldRawJSON, field.TypeString, value)
		_node.RawJSON = value
	}
	if value, ok := _c.mutation.LastCode(); ok {
		_spec.SetField(cardmailboxcredential.FieldLastCode, field.TypeString, value)
		_node.LastCode = &value
	}
	if value, ok := _c.mutation.LastStatus(); ok {
		_spec.SetField(cardmailboxcredential.FieldLastStatus, field.TypeString, value)
		_node.LastStatus = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(cardmailboxcredential.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.LastFetchedAt(); ok {
		_spec.SetField(cardmailboxcredential.FieldLastFetchedAt, field.TypeTime, value)
		_node.LastFetchedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CardMailboxCredential.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CardMailboxCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CardMailboxCredentialCreate) OnConflict(opts ...sql.ConflictOption) *CardMailboxCredentialUpsertOne {
	_c.conflict = opts
	return &CardMailboxCredentialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CardMailboxCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CardMailboxCredentialCreate) OnConflictColumns(columns ...string) *CardMailboxCredentialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CardMailboxCredentialUpsertOne{
		create: _c,
	}
}

type (
	// CardMailboxCredentialUpsertOne is the builder for "upsert"-ing
	//  one CardMailboxCredential node.
	CardMailboxCredentialUpsertOne struct {
		create *CardMailboxCredentialCreate
	}

	// CardMailboxCredentialUpsert is the "OnConflict" setter.
	CardMailboxCredentialUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CardMailboxCredentialUpsert) SetUpdatedAt(v time.Time) *CardMailboxCredentialUpsert {
	u.Set(cardmailboxcredential.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsert) UpdateUpdatedAt() *CardMailboxCredentialUpsert {
	u.SetExcluded(cardmailboxcredential.FieldUpdatedAt)
	return u
}

// SetEmail sets the "email" field.
func (u *CardMailboxCredentialUpsert) SetEmail(v string) *CardMailboxCredentialUpsert {
	u.Set(cardmailboxcredential.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsert) UpdateEmail() *CardMailboxCredentialUpsert {
	u.SetExcluded(cardmailboxcredential.FieldEmail)
	return u
}

// SetMailboxURL sets the "mailbox_url" field.
func (u *CardMailboxCredentialUpsert) SetMailboxURL(v string) *CardMailboxCredentialUpsert {
	u.Set(cardmailboxcredential.FieldMailboxURL, v)
	return u
}

// UpdateMailboxURL sets the "mailbox_url" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsert) UpdateMailboxURL() *CardMailboxCredentialUpsert {
	u.SetExcluded(cardmailboxcredential.FieldMailboxURL)
	return u
}

// SetRawJSON sets the "raw_json" field.
func (u *CardMailboxCredentialUpsert) SetRawJSON(v string) *CardMailboxCredentialUpsert {
	u.Set(cardmailboxcredential.FieldRawJSON, v)
	return u
}

// UpdateRawJSON sets the "raw_json" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsert) UpdateRawJSON() *CardMailboxCredentialUpsert {
	u.SetExcluded(cardmailboxcredential.FieldRawJSON)
	return u
}

// SetLastCode sets the "last_code" field.
func (u *CardMailboxCredentialUpsert) SetLastCode(v string) *CardMailboxCredentialUpsert {
	u.Set(cardmailboxcredential.FieldLastCode, v)
	return u
}

// UpdateLastCode sets the "last_code" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsert) UpdateLastCode() *CardMailboxCredentialUpsert {
	u.SetExcluded(cardmailboxcredential.FieldLastCode)
	return u
}

// ClearLastCode clears the value of the "last_code" field.
func (u *CardMailboxCredentialUpsert) ClearLastCode() *CardMailboxCredentialUpsert {
	u.SetNull(cardmailboxcredential.FieldLastCode)
	return u
}

// SetLastStatus sets the "last_status" field.
func (u *CardMailboxCredentialUpsert) SetLastStatus(v string) *CardMailboxCredentialUpsert {
	u.Set(cardmailboxcredential.FieldLastStatus, v)
	return u
}

// UpdateLastStatus sets the "last_status" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsert) UpdateLastStatus() *CardMailboxCredentialUpsert {
	u.SetExcluded(cardmailboxcredential.FieldLastStatus)
	return u
}

// ClearLastStatus clears the value of the "last_status" field.
func (u *CardMailboxCredentialUpsert) ClearLastStatus() *CardMailboxCredentialUpsert {
	u.SetNull(cardmailboxcredential.FieldLastStatus)
	return u
}

// SetLastError sets the "last_error" field.
func (u *CardMailboxCredentialUpsert) SetLastError(v string) *CardMailboxCredentialUpsert {
	u.Set(cardmailboxcredential.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsert) UpdateLastError() *CardMailboxCredentialUpsert {
	u.SetExcluded(cardmailboxcredential.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *CardMailboxCredentialUpsert) ClearLastError() *CardMailboxCredentialUpsert {
	u.SetNull(cardmailboxcredential.FieldLastError)
	return u
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (u *CardMailboxCredentialUpsert) SetLastFetchedAt(v time.Time) *CardMailboxCredentialUpsert {
	u.Set(cardmailboxcredential.FieldLastFetchedAt, v)
	return u
}

// UpdateLastFetchedAt sets the "last_fetched_at" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsert) UpdateLastFetchedAt() *CardMailboxCredentialUpsert {
	u.SetExcluded(cardmailboxcredential.FieldLastFetchedAt)
	return u
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (u *CardMailboxCredentialUpsert) ClearLastFetchedAt() *CardMailboxCredentialUpsert {
	u.SetNull(cardmailboxcredential.FieldLastFetchedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CardMailboxCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CardMailboxCredentialUpsertOne) UpdateNewValues() *CardMailboxCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(cardmailboxcredential.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CardMailboxCredential.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CardMailboxCredentialUpsertOne) Ignore() *CardMailboxCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CardMailboxCredentialUpsertOne) DoNothing() *CardMailboxCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CardMailboxCredentialCreate.OnConflict
// documentation for more info.
func (u *CardMailboxCredentialUpsertOne) Update(set func(*CardMailboxCredentialUpsert)) *CardMailboxCredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CardMailboxCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CardMailboxCredentialUpsertOne) SetUpdatedAt(v time.Time) *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertOne) UpdateUpdatedAt() *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEmail sets the "email" field.
func (u *CardMailboxCredentialUpsertOne) SetEmail(v string) *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertOne) UpdateEmail() *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateEmail()
	})
}

// SetMailboxURL sets the "mailbox_url" field.
func (u *CardMailboxCredentialUpsertOne) SetMailboxURL(v string) *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetMailboxURL(v)
	})
}

// UpdateMailboxURL sets the "mailbox_url" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertOne) UpdateMailboxURL() *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateMailboxURL()
	})
}

// SetRawJSON sets the "raw_json" field.
func (u *CardMailboxCredentialUpsertOne) SetRawJSON(v string) *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetRawJSON(v)
	})
}

// UpdateRawJSON sets the "raw_json" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertOne) UpdateRawJSON() *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateRawJSON()
	})
}

// SetLastCode sets the "last_code" field.
func (u *CardMailboxCredentialUpsertOne) SetLastCode(v string) *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetLastCode(v)
	})
}

// UpdateLastCode sets the "last_code" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertOne) UpdateLastCode() *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateLastCode()
	})
}

// ClearLastCode clears the value of the "last_code" field.
func (u *CardMailboxCredentialUpsertOne) ClearLastCode() *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.ClearLastCode()
	})
}

// SetLastStatus sets the "last_status" field.
func (u *CardMailboxCredentialUpsertOne) SetLastStatus(v string) *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetLastStatus(v)
	})
}

// UpdateLastStatus sets the "last_status" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertOne) UpdateLastStatus() *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateLastStatus()
	})
}

// ClearLastStatus clears the value of the "last_status" field.
func (u *CardMailboxCredentialUpsertOne) ClearLastStatus() *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.ClearLastStatus()
	})
}

// SetLastError sets the "last_error" field.
func (u *CardMailboxCredentialUpsertOne) SetLastError(v string) *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertOne) UpdateLastError() *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *CardMailboxCredentialUpsertOne) ClearLastError() *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.ClearLastError()
	})
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (u *CardMailboxCredentialUpsertOne) SetLastFetchedAt(v time.Time) *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetLastFetchedAt(v)
	})
}

// UpdateLastFetchedAt sets the "last_fetched_at" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertOne) UpdateLastFetchedAt() *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateLastFetchedAt()
	})
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (u *CardMailboxCredentialUpsertOne) ClearLastFetchedAt() *CardMailboxCredentialUpsertOne {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.ClearLastFetchedAt()
	})
}

// Exec executes the query.
func (u *CardMailboxCredentialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CardMailboxCredentialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CardMailboxCredentialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CardMailboxCredentialUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CardMailboxCredentialUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CardMailboxCredentialCreateBulk is the builder for creating many CardMailboxCredential entities in bulk.
type CardMailboxCredentialCreateBulk struct {
	config
	err      error
	builders []*CardMailboxCredentialCreate
	conflict []sql.ConflictOption
}

// Save creates the CardMailboxCredential entities in the database.
func (_c *CardMailboxCredentialCreateBulk) Save(ctx context.Context) ([]*CardMailboxCredential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CardMailboxCredential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CardMailboxCredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CardMailboxCredentialCreateBulk) SaveX(ctx context.Context) []*CardMailboxCredential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CardMailboxCredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CardMailboxCredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CardMailboxCredential.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CardMailboxCredentialUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CardMailboxCredentialCreateBulk) OnConflict(opts ...sql.ConflictOption) *CardMailboxCredentialUpsertBulk {
	_c.conflict = opts
	return &CardMailboxCredentialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CardMailboxCredential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CardMailboxCredentialCreateBulk) OnConflictColumns(columns ...string) *CardMailboxCredentialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CardMailboxCredentialUpsertBulk{
		create: _c,
	}
}

// CardMailboxCredentialUpsertBulk is the builder for "upsert"-ing
// a bulk of CardMailboxCredential nodes.
type CardMailboxCredentialUpsertBulk struct {
	create *CardMailboxCredentialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CardMailboxCredential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CardMailboxCredentialUpsertBulk) UpdateNewValues() *CardMailboxCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(cardmailboxcredential.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CardMailboxCredential.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CardMailboxCredentialUpsertBulk) Ignore() *CardMailboxCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CardMailboxCredentialUpsertBulk) DoNothing() *CardMailboxCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CardMailboxCredentialCreateBulk.OnConflict
// documentation for more info.
func (u *CardMailboxCredentialUpsertBulk) Update(set func(*CardMailboxCredentialUpsert)) *CardMailboxCredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CardMailboxCredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CardMailboxCredentialUpsertBulk) SetUpdatedAt(v time.Time) *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertBulk) UpdateUpdatedAt() *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEmail sets the "email" field.
func (u *CardMailboxCredentialUpsertBulk) SetEmail(v string) *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertBulk) UpdateEmail() *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateEmail()
	})
}

// SetMailboxURL sets the "mailbox_url" field.
func (u *CardMailboxCredentialUpsertBulk) SetMailboxURL(v string) *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetMailboxURL(v)
	})
}

// UpdateMailboxURL sets the "mailbox_url" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertBulk) UpdateMailboxURL() *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateMailboxURL()
	})
}

// SetRawJSON sets the "raw_json" field.
func (u *CardMailboxCredentialUpsertBulk) SetRawJSON(v string) *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetRawJSON(v)
	})
}

// UpdateRawJSON sets the "raw_json" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertBulk) UpdateRawJSON() *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateRawJSON()
	})
}

// SetLastCode sets the "last_code" field.
func (u *CardMailboxCredentialUpsertBulk) SetLastCode(v string) *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetLastCode(v)
	})
}

// UpdateLastCode sets the "last_code" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertBulk) UpdateLastCode() *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateLastCode()
	})
}

// ClearLastCode clears the value of the "last_code" field.
func (u *CardMailboxCredentialUpsertBulk) ClearLastCode() *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.ClearLastCode()
	})
}

// SetLastStatus sets the "last_status" field.
func (u *CardMailboxCredentialUpsertBulk) SetLastStatus(v string) *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetLastStatus(v)
	})
}

// UpdateLastStatus sets the "last_status" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertBulk) UpdateLastStatus() *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateLastStatus()
	})
}

// ClearLastStatus clears the value of the "last_status" field.
func (u *CardMailboxCredentialUpsertBulk) ClearLastStatus() *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.ClearLastStatus()
	})
}

// SetLastError sets the "last_error" field.
func (u *CardMailboxCredentialUpsertBulk) SetLastError(v string) *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertBulk) UpdateLastError() *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *CardMailboxCredentialUpsertBulk) ClearLastError() *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.ClearLastError()
	})
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (u *CardMailboxCredentialUpsertBulk) SetLastFetchedAt(v time.Time) *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.SetLastFetchedAt(v)
	})
}

// UpdateLastFetchedAt sets the "last_fetched_at" field to the value that was provided on create.
func (u *CardMailboxCredentialUpsertBulk) UpdateLastFetchedAt() *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.UpdateLastFetchedAt()
	})
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (u *CardMailboxCredentialUpsertBulk) ClearLastFetchedAt() *CardMailboxCredentialUpsertBulk {
	return u.Update(func(s *CardMailboxCredentialUpsert) {
		s.ClearLastFetchedAt()
	})
}

// Exec executes the query.
func (u *CardMailboxCredentialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CardMailboxCredentialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CardMailboxCredentialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CardMailboxCredentialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
