// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cardmailboxcredential"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CardMailboxCredentialDelete is the builder for deleting a CardMailboxCredential entity.
type CardMailboxCredentialDelete struct {
	config
	hooks    []Hook
	mutation *CardMailboxCredentialMutation
}

// Where appends a list predicates to the CardMailboxCredentialDelete builder.
func (_d *CardMailboxCredentialDelete) Where(ps ...predicate.CardMailboxCredential) *CardMailboxCredentialDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CardMailboxCredentialDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CardMailboxCredentialDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CardMailboxCredentialDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cardmailboxcredential.Table, sqlgraph.NewFieldSpec(cardmailboxcredential.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CardMailboxCredentialDeleteOne is the builder for deleting a single CardMailboxCredential entity.
type CardMailboxCredentialDeleteOne struct {
	_d *CardMailboxCredentialDelete
}

// Where appends a list predicates to the CardMailboxCredentialDelete builder.
func (_d *CardMailboxCredentialDeleteOne) Where(ps ...predicate.CardMailboxCredential) *CardMailboxCredentialDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CardMailboxCredentialDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cardmailboxcredential.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CardMailboxCredentialDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
