// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/cardmailboxcredential"
)

// CardMailboxCredential is the model entity for the CardMailboxCredential schema.
type CardMailboxCredential struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// MailboxURL holds the value of the "mailbox_url" field.
	MailboxURL string `json:"mailbox_url,omitempty"`
	// LastCode holds the value of the "last_code" field.
	LastCode *string `json:"last_code,omitempty"`
	// LastStatus holds the value of the "last_status" field.
	LastStatus *string `json:"last_status,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// LastFetchedAt holds the value of the "last_fetched_at" field.
	LastFetchedAt *time.Time `json:"last_fetched_at,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CardMailboxCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cardmailboxcredential.FieldID:
			values[i] = new(sql.NullInt64)
		case cardmailboxcredential.FieldEmail, cardmailboxcredential.FieldMailboxURL, cardmailboxcredential.FieldLastCode, cardmailboxcredential.FieldLastStatus, cardmailboxcredential.FieldLastError:
			values[i] = new(sql.NullString)
		case cardmailboxcredential.FieldCreatedAt, cardmailboxcredential.FieldUpdatedAt, cardmailboxcredential.FieldLastFetchedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CardMailboxCredential fields.
func (_m *CardMailboxCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cardmailboxcredential.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case cardmailboxcredential.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case cardmailboxcredential.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case cardmailboxcredential.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case cardmailboxcredential.FieldMailboxURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mailbox_url", values[i])
			} else if value.Valid {
				_m.MailboxURL = value.String
			}
		case cardmailboxcredential.FieldLastCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_code", values[i])
			} else if value.Valid {
				_m.LastCode = new(string)
				*_m.LastCode = value.String
			}
		case cardmailboxcredential.FieldLastStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_status", values[i])
			} else if value.Valid {
				_m.LastStatus = new(string)
				*_m.LastStatus = value.String
			}
		case cardmailboxcredential.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case cardmailboxcredential.FieldLastFetchedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_fetched_at", values[i])
			} else if value.Valid {
				_m.LastFetchedAt = new(time.Time)
				*_m.LastFetchedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CardMailboxCredential.
// This includes values selected through modifiers, order, etc.
func (_m *CardMailboxCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CardMailboxCredential.
// Note that you need to call CardMailboxCredential.Unwrap() before calling this method if this CardMailboxCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CardMailboxCredential) Update() *CardMailboxCredentialUpdateOne {
	return NewCardMailboxCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CardMailboxCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CardMailboxCredential) Unwrap() *CardMailboxCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CardMailboxCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CardMailboxCredential) String() string {
	var builder strings.Builder
	builder.WriteString("CardMailboxCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("mailbox_url=")
	builder.WriteString(_m.MailboxURL)
	builder.WriteString(", ")
	if v := _m.LastCode; v != nil {
		builder.WriteString("last_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastStatus; v != nil {
		builder.WriteString("last_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastFetchedAt; v != nil {
		builder.WriteString("last_fetched_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// CardMailboxCredentials is a parsable slice of CardMailboxCredential.
type CardMailboxCredentials []*CardMailboxCredential
