// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/cardmailboxcredential"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CardMailboxCredentialUpdate is the builder for updating CardMailboxCredential entities.
type CardMailboxCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *CardMailboxCredentialMutation
}

// Where appends a list predicates to the CardMailboxCredentialUpdate builder.
func (_u *CardMailboxCredentialUpdate) Where(ps ...predicate.CardMailboxCredential) *CardMailboxCredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CardMailboxCredentialUpdate) SetUpdatedAt(v time.Time) *CardMailboxCredentialUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *CardMailboxCredentialUpdate) SetEmail(v string) *CardMailboxCredentialUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdate) SetNillableEmail(v *string) *CardMailboxCredentialUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetMailboxURL sets the "mailbox_url" field.
func (_u *CardMailboxCredentialUpdate) SetMailboxURL(v string) *CardMailboxCredentialUpdate {
	_u.mutation.SetMailboxURL(v)
	return _u
}

// SetNillableMailboxURL sets the "mailbox_url" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdate) SetNillableMailboxURL(v *string) *CardMailboxCredentialUpdate {
	if v != nil {
		_u.SetMailboxURL(*v)
	}
	return _u
}

// SetRawJSON sets the "raw_json" field.
func (_u *CardMailboxCredentialUpdate) SetRawJSON(v string) *CardMailboxCredentialUpdate {
	_u.mutation.SetRawJSON(v)
	return _u
}

// SetNillableRawJSON sets the "raw_json" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdate) SetNillableRawJSON(v *string) *CardMailboxCredentialUpdate {
	if v != nil {
		_u.SetRawJSON(*v)
	}
	return _u
}

// SetLastCode sets the "last_code" field.
func (_u *CardMailboxCredentialUpdate) SetLastCode(v string) *CardMailboxCredentialUpdate {
	_u.mutation.SetLastCode(v)
	return _u
}

// SetNillableLastCode sets the "last_code" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdate) SetNillableLastCode(v *string) *CardMailboxCredentialUpdate {
	if v != nil {
		_u.SetLastCode(*v)
	}
	return _u
}

// ClearLastCode clears the value of the "last_code" field.
func (_u *CardMailboxCredentialUpdate) ClearLastCode() *CardMailboxCredentialUpdate {
	_u.mutation.ClearLastCode()
	return _u
}

// SetLastStatus sets the "last_status" field.
func (_u *CardMailboxCredentialUpdate) SetLastStatus(v string) *CardMailboxCredentialUpdate {
	_u.mutation.SetLastStatus(v)
	return _u
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdate) SetNillableLastStatus(v *string) *CardMailboxCredentialUpdate {
	if v != nil {
		_u.SetLastStatus(*v)
	}
	return _u
}

// ClearLastStatus clears the value of the "last_status" field.
func (_u *CardMailboxCredentialUpdate) ClearLastStatus() *CardMailboxCredentialUpdate {
	_u.mutation.ClearLastStatus()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CardMailboxCredentialUpdate) SetLastError(v string) *CardMailboxCredentialUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdate) SetNillableLastError(v *string) *CardMailboxCredentialUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CardMailboxCredentialUpdate) ClearLastError() *CardMailboxCredentialUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (_u *CardMailboxCredentialUpdate) SetLastFetchedAt(v time.Time) *CardMailboxCredentialUpdate {
	_u.mutation.SetLastFetchedAt(v)
	return _u
}

// SetNillableLastFetchedAt sets the "last_fetched_at" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdate) SetNillableLastFetchedAt(v *time.Time) *CardMailboxCredentialUpdate {
	if v != nil {
		_u.SetLastFetchedAt(*v)
	}
	return _u
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (_u *CardMailboxCredentialUpdate) ClearLastFetchedAt() *CardMailboxCredentialUpdate {
	_u.mutation.ClearLastFetchedAt()
	return _u
}

// Mutation returns the CardMailboxCredentialMutation object of the builder.
func (_u *CardMailboxCredentialUpdate) Mutation() *CardMailboxCredentialMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CardMailboxCredentialUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardMailboxCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CardMailboxCredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardMailboxCredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CardMailboxCredentialUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cardmailboxcredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardMailboxCredentialUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := cardmailboxcredential.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MailboxURL(); ok {
		if err := cardmailboxcredential.MailboxURLValidator(v); err != nil {
			return &ValidationError{Name: "mailbox_url", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.mailbox_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RawJSON(); ok {
		if err := cardmailboxcredential.RawJSONValidator(v); err != nil {
			return &ValidationError{Name: "raw_json", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.raw_json": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastCode(); ok {
		if err := cardmailboxcredential.LastCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_code", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.last_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastStatus(); ok {
		if err := cardmailboxcredential.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.last_status": %w`, err)}
		}
	}
	return nil
}

func (_u *CardMailboxCredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cardmailboxcredential.Table, cardmailboxcredential.Columns, sqlgraph.NewFieldSpec(cardmailboxcredential.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cardmailboxcredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(cardmailboxcredential.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.MailboxURL(); ok {
		_spec.SetField(cardmailboxcredential.FieldMailboxURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawJSON(); ok {
		_spec.SetField(cardmailboxcredential.FieldRawJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastCode(); ok {
		_spec.SetField(cardmailboxcredential.FieldLastCode, field.TypeString, value)
	}
	if _u.mutation.LastCodeCleared() {
		_spec.ClearField(cardmailboxcredential.FieldLastCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastStatus(); ok {
		_spec.SetField(cardmailboxcredential.FieldLastStatus, field.TypeString, value)
	}
	if _u.mutation.LastStatusCleared() {
		_spec.ClearField(cardmailboxcredential.FieldLastStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(cardmailboxcredential.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(cardmailboxcredential.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastFetchedAt(); ok {
		_spec.SetField(cardmailboxcredential.FieldLastFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.LastFetchedAtCleared() {
		_spec.ClearField(cardmailboxcredential.FieldLastFetchedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cardmailboxcredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CardMailboxCredentialUpdateOne is the builder for updating a single CardMailboxCredential entity.
type CardMailboxCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CardMailboxCredentialMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CardMailboxCredentialUpdateOne) SetUpdatedAt(v time.Time) *CardMailboxCredentialUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *CardMailboxCredentialUpdateOne) SetEmail(v string) *CardMailboxCredentialUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdateOne) SetNillableEmail(v *string) *CardMailboxCredentialUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetMailboxURL sets the "mailbox_url" field.
func (_u *CardMailboxCredentialUpdateOne) SetMailboxURL(v string) *CardMailboxCredentialUpdateOne {
	_u.mutation.SetMailboxURL(v)
	return _u
}

// SetNillableMailboxURL sets the "mailbox_url" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdateOne) SetNillableMailboxURL(v *string) *CardMailboxCredentialUpdateOne {
	if v != nil {
		_u.SetMailboxURL(*v)
	}
	return _u
}

// SetRawJSON sets the "raw_json" field.
func (_u *CardMailboxCredentialUpdateOne) SetRawJSON(v string) *CardMailboxCredentialUpdateOne {
	_u.mutation.SetRawJSON(v)
	return _u
}

// SetNillableRawJSON sets the "raw_json" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdateOne) SetNillableRawJSON(v *string) *CardMailboxCredentialUpdateOne {
	if v != nil {
		_u.SetRawJSON(*v)
	}
	return _u
}

// SetLastCode sets the "last_code" field.
func (_u *CardMailboxCredentialUpdateOne) SetLastCode(v string) *CardMailboxCredentialUpdateOne {
	_u.mutation.SetLastCode(v)
	return _u
}

// SetNillableLastCode sets the "last_code" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdateOne) SetNillableLastCode(v *string) *CardMailboxCredentialUpdateOne {
	if v != nil {
		_u.SetLastCode(*v)
	}
	return _u
}

// ClearLastCode clears the value of the "last_code" field.
func (_u *CardMailboxCredentialUpdateOne) ClearLastCode() *CardMailboxCredentialUpdateOne {
	_u.mutation.ClearLastCode()
	return _u
}

// SetLastStatus sets the "last_status" field.
func (_u *CardMailboxCredentialUpdateOne) SetLastStatus(v string) *CardMailboxCredentialUpdateOne {
	_u.mutation.SetLastStatus(v)
	return _u
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdateOne) SetNillableLastStatus(v *string) *CardMailboxCredentialUpdateOne {
	if v != nil {
		_u.SetLastStatus(*v)
	}
	return _u
}

// ClearLastStatus clears the value of the "last_status" field.
func (_u *CardMailboxCredentialUpdateOne) ClearLastStatus() *CardMailboxCredentialUpdateOne {
	_u.mutation.ClearLastStatus()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CardMailboxCredentialUpdateOne) SetLastError(v string) *CardMailboxCredentialUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdateOne) SetNillableLastError(v *string) *CardMailboxCredentialUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CardMailboxCredentialUpdateOne) ClearLastError() *CardMailboxCredentialUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (_u *CardMailboxCredentialUpdateOne) SetLastFetchedAt(v time.Time) *CardMailboxCredentialUpdateOne {
	_u.mutation.SetLastFetchedAt(v)
	return _u
}

// SetNillableLastFetchedAt sets the "last_fetched_at" field if the given value is not nil.
func (_u *CardMailboxCredentialUpdateOne) SetNillableLastFetchedAt(v *time.Time) *CardMailboxCredentialUpdateOne {
	if v != nil {
		_u.SetLastFetchedAt(*v)
	}
	return _u
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (_u *CardMailboxCredentialUpdateOne) ClearLastFetchedAt() *CardMailboxCredentialUpdateOne {
	_u.mutation.ClearLastFetchedAt()
	return _u
}

// Mutation returns the CardMailboxCredentialMutation object of the builder.
func (_u *CardMailboxCredentialUpdateOne) Mutation() *CardMailboxCredentialMutation {
	return _u.mutation
}

// Where appends a list predicates to the CardMailboxCredentialUpdate builder.
func (_u *CardMailboxCredentialUpdateOne) Where(ps ...predicate.CardMailboxCredential) *CardMailboxCredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CardMailboxCredentialUpdateOne) Select(field string, fields ...string) *CardMailboxCredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CardMailboxCredential entity.
func (_u *CardMailboxCredentialUpdateOne) Save(ctx context.Context) (*CardMailboxCredential, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CardMailboxCredentialUpdateOne) SaveX(ctx context.Context) *CardMailboxCredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CardMailboxCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CardMailboxCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CardMailboxCredentialUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := cardmailboxcredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CardMailboxCredentialUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := cardmailboxcredential.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MailboxURL(); ok {
		if err := cardmailboxcredential.MailboxURLValidator(v); err != nil {
			return &ValidationError{Name: "mailbox_url", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.mailbox_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RawJSON(); ok {
		if err := cardmailboxcredential.RawJSONValidator(v); err != nil {
			return &ValidationError{Name: "raw_json", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.raw_json": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastCode(); ok {
		if err := cardmailboxcredential.LastCodeValidator(v); err != nil {
			return &ValidationError{Name: "last_code", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.last_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastStatus(); ok {
		if err := cardmailboxcredential.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "CardMailboxCredential.last_status": %w`, err)}
		}
	}
	return nil
}

func (_u *CardMailboxCredentialUpdateOne) sqlSave(ctx context.Context) (_node *CardMailboxCredential, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cardmailboxcredential.Table, cardmailboxcredential.Columns, sqlgraph.NewFieldSpec(cardmailboxcredential.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CardMailboxCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cardmailboxcredential.FieldID)
		for _, f := range fields {
			if !cardmailboxcredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cardmailboxcredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(cardmailboxcredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(cardmailboxcredential.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.MailboxURL(); ok {
		_spec.SetField(cardmailboxcredential.FieldMailboxURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawJSON(); ok {
		_spec.SetField(cardmailboxcredential.FieldRawJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastCode(); ok {
		_spec.SetField(cardmailboxcredential.FieldLastCode, field.TypeString, value)
	}
	if _u.mutation.LastCodeCleared() {
		_spec.ClearField(cardmailboxcredential.FieldLastCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastStatus(); ok {
		_spec.SetField(cardmailboxcredential.FieldLastStatus, field.TypeString, value)
	}
	if _u.mutation.LastStatusCleared() {
		_spec.ClearField(cardmailboxcredential.FieldLastStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(cardmailboxcredential.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(cardmailboxcredential.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastFetchedAt(); ok {
		_spec.SetField(cardmailboxcredential.FieldLastFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.LastFetchedAtCleared() {
		_spec.ClearField(cardmailboxcredential.FieldLastFetchedAt, field.TypeTime)
	}
	_node = &CardMailboxCredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cardmailboxcredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
