// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/microsoftemailaccount"
)

// MicrosoftEmailAccount is the model entity for the MicrosoftEmailAccount schema.
type MicrosoftEmailAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// RefreshToken holds the value of the "refresh_token" field.
	RefreshToken string `json:"refresh_token,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// LastCheckAt holds the value of the "last_check_at" field.
	LastCheckAt *time.Time `json:"last_check_at,omitempty"`
	// LastFetchAt holds the value of the "last_fetch_at" field.
	LastFetchAt *time.Time `json:"last_fetch_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes        *string `json:"notes,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MicrosoftEmailAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case microsoftemailaccount.FieldID:
			values[i] = new(sql.NullInt64)
		case microsoftemailaccount.FieldEmail, microsoftemailaccount.FieldPassword, microsoftemailaccount.FieldClientID, microsoftemailaccount.FieldRefreshToken, microsoftemailaccount.FieldStatus, microsoftemailaccount.FieldLastError, microsoftemailaccount.FieldNotes:
			values[i] = new(sql.NullString)
		case microsoftemailaccount.FieldCreatedAt, microsoftemailaccount.FieldUpdatedAt, microsoftemailaccount.FieldLastCheckAt, microsoftemailaccount.FieldLastFetchAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MicrosoftEmailAccount fields.
func (_m *MicrosoftEmailAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case microsoftemailaccount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case microsoftemailaccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case microsoftemailaccount.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case microsoftemailaccount.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case microsoftemailaccount.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case microsoftemailaccount.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case microsoftemailaccount.FieldRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value.Valid {
				_m.RefreshToken = value.String
			}
		case microsoftemailaccount.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case microsoftemailaccount.FieldLastCheckAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_check_at", values[i])
			} else if value.Valid {
				_m.LastCheckAt = new(time.Time)
				*_m.LastCheckAt = value.Time
			}
		case microsoftemailaccount.FieldLastFetchAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_fetch_at", values[i])
			} else if value.Valid {
				_m.LastFetchAt = new(time.Time)
				*_m.LastFetchAt = value.Time
			}
		case microsoftemailaccount.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case microsoftemailaccount.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MicrosoftEmailAccount.
// This includes values selected through modifiers, order, etc.
func (_m *MicrosoftEmailAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MicrosoftEmailAccount.
// Note that you need to call MicrosoftEmailAccount.Unwrap() before calling this method if this MicrosoftEmailAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MicrosoftEmailAccount) Update() *MicrosoftEmailAccountUpdateOne {
	return NewMicrosoftEmailAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MicrosoftEmailAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MicrosoftEmailAccount) Unwrap() *MicrosoftEmailAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MicrosoftEmailAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MicrosoftEmailAccount) String() string {
	var builder strings.Builder
	builder.WriteString("MicrosoftEmailAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(_m.Password)
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("refresh_token=")
	builder.WriteString(_m.RefreshToken)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.LastCheckAt; v != nil {
		builder.WriteString("last_check_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastFetchAt; v != nil {
		builder.WriteString("last_fetch_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// MicrosoftEmailAccounts is a parsable slice of MicrosoftEmailAccount.
type MicrosoftEmailAccounts []*MicrosoftEmailAccount
