// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/microsoftemailaccount"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// MicrosoftEmailAccountUpdate is the builder for updating MicrosoftEmailAccount entities.
type MicrosoftEmailAccountUpdate struct {
	config
	hooks    []Hook
	mutation *MicrosoftEmailAccountMutation
}

// Where appends a list predicates to the MicrosoftEmailAccountUpdate builder.
func (_u *MicrosoftEmailAccountUpdate) Where(ps ...predicate.MicrosoftEmailAccount) *MicrosoftEmailAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MicrosoftEmailAccountUpdate) SetUpdatedAt(v time.Time) *MicrosoftEmailAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *MicrosoftEmailAccountUpdate) SetEmail(v string) *MicrosoftEmailAccountUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdate) SetNillableEmail(v *string) *MicrosoftEmailAccountUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *MicrosoftEmailAccountUpdate) SetPassword(v string) *MicrosoftEmailAccountUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdate) SetNillablePassword(v *string) *MicrosoftEmailAccountUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *MicrosoftEmailAccountUpdate) SetClientID(v string) *MicrosoftEmailAccountUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdate) SetNillableClientID(v *string) *MicrosoftEmailAccountUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *MicrosoftEmailAccountUpdate) SetRefreshToken(v string) *MicrosoftEmailAccountUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdate) SetNillableRefreshToken(v *string) *MicrosoftEmailAccountUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MicrosoftEmailAccountUpdate) SetStatus(v string) *MicrosoftEmailAccountUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdate) SetNillableStatus(v *string) *MicrosoftEmailAccountUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastCheckAt sets the "last_check_at" field.
func (_u *MicrosoftEmailAccountUpdate) SetLastCheckAt(v time.Time) *MicrosoftEmailAccountUpdate {
	_u.mutation.SetLastCheckAt(v)
	return _u
}

// SetNillableLastCheckAt sets the "last_check_at" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdate) SetNillableLastCheckAt(v *time.Time) *MicrosoftEmailAccountUpdate {
	if v != nil {
		_u.SetLastCheckAt(*v)
	}
	return _u
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (_u *MicrosoftEmailAccountUpdate) ClearLastCheckAt() *MicrosoftEmailAccountUpdate {
	_u.mutation.ClearLastCheckAt()
	return _u
}

// SetLastFetchAt sets the "last_fetch_at" field.
func (_u *MicrosoftEmailAccountUpdate) SetLastFetchAt(v time.Time) *MicrosoftEmailAccountUpdate {
	_u.mutation.SetLastFetchAt(v)
	return _u
}

// SetNillableLastFetchAt sets the "last_fetch_at" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdate) SetNillableLastFetchAt(v *time.Time) *MicrosoftEmailAccountUpdate {
	if v != nil {
		_u.SetLastFetchAt(*v)
	}
	return _u
}

// ClearLastFetchAt clears the value of the "last_fetch_at" field.
func (_u *MicrosoftEmailAccountUpdate) ClearLastFetchAt() *MicrosoftEmailAccountUpdate {
	_u.mutation.ClearLastFetchAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *MicrosoftEmailAccountUpdate) SetLastError(v string) *MicrosoftEmailAccountUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdate) SetNillableLastError(v *string) *MicrosoftEmailAccountUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *MicrosoftEmailAccountUpdate) ClearLastError() *MicrosoftEmailAccountUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *MicrosoftEmailAccountUpdate) SetNotes(v string) *MicrosoftEmailAccountUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdate) SetNillableNotes(v *string) *MicrosoftEmailAccountUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *MicrosoftEmailAccountUpdate) ClearNotes() *MicrosoftEmailAccountUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the MicrosoftEmailAccountMutation object of the builder.
func (_u *MicrosoftEmailAccountUpdate) Mutation() *MicrosoftEmailAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MicrosoftEmailAccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MicrosoftEmailAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MicrosoftEmailAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MicrosoftEmailAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MicrosoftEmailAccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := microsoftemailaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MicrosoftEmailAccountUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := microsoftemailaccount.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := microsoftemailaccount.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := microsoftemailaccount.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefreshToken(); ok {
		if err := microsoftemailaccount.RefreshTokenValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.refresh_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := microsoftemailaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.status": %w`, err)}
		}
	}
	return nil
}

func (_u *MicrosoftEmailAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(microsoftemailaccount.Table, microsoftemailaccount.Columns, sqlgraph.NewFieldSpec(microsoftemailaccount.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(microsoftemailaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(microsoftemailaccount.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(microsoftemailaccount.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(microsoftemailaccount.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(microsoftemailaccount.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(microsoftemailaccount.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastCheckAt(); ok {
		_spec.SetField(microsoftemailaccount.FieldLastCheckAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckAtCleared() {
		_spec.ClearField(microsoftemailaccount.FieldLastCheckAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastFetchAt(); ok {
		_spec.SetField(microsoftemailaccount.FieldLastFetchAt, field.TypeTime, value)
	}
	if _u.mutation.LastFetchAtCleared() {
		_spec.ClearField(microsoftemailaccount.FieldLastFetchAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(microsoftemailaccount.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(microsoftemailaccount.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(microsoftemailaccount.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(microsoftemailaccount.FieldNotes, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{microsoftemailaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MicrosoftEmailAccountUpdateOne is the builder for updating a single MicrosoftEmailAccount entity.
type MicrosoftEmailAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MicrosoftEmailAccountMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MicrosoftEmailAccountUpdateOne) SetUpdatedAt(v time.Time) *MicrosoftEmailAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *MicrosoftEmailAccountUpdateOne) SetEmail(v string) *MicrosoftEmailAccountUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdateOne) SetNillableEmail(v *string) *MicrosoftEmailAccountUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *MicrosoftEmailAccountUpdateOne) SetPassword(v string) *MicrosoftEmailAccountUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdateOne) SetNillablePassword(v *string) *MicrosoftEmailAccountUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *MicrosoftEmailAccountUpdateOne) SetClientID(v string) *MicrosoftEmailAccountUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdateOne) SetNillableClientID(v *string) *MicrosoftEmailAccountUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *MicrosoftEmailAccountUpdateOne) SetRefreshToken(v string) *MicrosoftEmailAccountUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdateOne) SetNillableRefreshToken(v *string) *MicrosoftEmailAccountUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MicrosoftEmailAccountUpdateOne) SetStatus(v string) *MicrosoftEmailAccountUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdateOne) SetNillableStatus(v *string) *MicrosoftEmailAccountUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastCheckAt sets the "last_check_at" field.
func (_u *MicrosoftEmailAccountUpdateOne) SetLastCheckAt(v time.Time) *MicrosoftEmailAccountUpdateOne {
	_u.mutation.SetLastCheckAt(v)
	return _u
}

// SetNillableLastCheckAt sets the "last_check_at" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdateOne) SetNillableLastCheckAt(v *time.Time) *MicrosoftEmailAccountUpdateOne {
	if v != nil {
		_u.SetLastCheckAt(*v)
	}
	return _u
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (_u *MicrosoftEmailAccountUpdateOne) ClearLastCheckAt() *MicrosoftEmailAccountUpdateOne {
	_u.mutation.ClearLastCheckAt()
	return _u
}

// SetLastFetchAt sets the "last_fetch_at" field.
func (_u *MicrosoftEmailAccountUpdateOne) SetLastFetchAt(v time.Time) *MicrosoftEmailAccountUpdateOne {
	_u.mutation.SetLastFetchAt(v)
	return _u
}

// SetNillableLastFetchAt sets the "last_fetch_at" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdateOne) SetNillableLastFetchAt(v *time.Time) *MicrosoftEmailAccountUpdateOne {
	if v != nil {
		_u.SetLastFetchAt(*v)
	}
	return _u
}

// ClearLastFetchAt clears the value of the "last_fetch_at" field.
func (_u *MicrosoftEmailAccountUpdateOne) ClearLastFetchAt() *MicrosoftEmailAccountUpdateOne {
	_u.mutation.ClearLastFetchAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *MicrosoftEmailAccountUpdateOne) SetLastError(v string) *MicrosoftEmailAccountUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdateOne) SetNillableLastError(v *string) *MicrosoftEmailAccountUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *MicrosoftEmailAccountUpdateOne) ClearLastError() *MicrosoftEmailAccountUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *MicrosoftEmailAccountUpdateOne) SetNotes(v string) *MicrosoftEmailAccountUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *MicrosoftEmailAccountUpdateOne) SetNillableNotes(v *string) *MicrosoftEmailAccountUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *MicrosoftEmailAccountUpdateOne) ClearNotes() *MicrosoftEmailAccountUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// Mutation returns the MicrosoftEmailAccountMutation object of the builder.
func (_u *MicrosoftEmailAccountUpdateOne) Mutation() *MicrosoftEmailAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the MicrosoftEmailAccountUpdate builder.
func (_u *MicrosoftEmailAccountUpdateOne) Where(ps ...predicate.MicrosoftEmailAccount) *MicrosoftEmailAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MicrosoftEmailAccountUpdateOne) Select(field string, fields ...string) *MicrosoftEmailAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MicrosoftEmailAccount entity.
func (_u *MicrosoftEmailAccountUpdateOne) Save(ctx context.Context) (*MicrosoftEmailAccount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MicrosoftEmailAccountUpdateOne) SaveX(ctx context.Context) *MicrosoftEmailAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MicrosoftEmailAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MicrosoftEmailAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MicrosoftEmailAccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := microsoftemailaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MicrosoftEmailAccountUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := microsoftemailaccount.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := microsoftemailaccount.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := microsoftemailaccount.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefreshToken(); ok {
		if err := microsoftemailaccount.RefreshTokenValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.refresh_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := microsoftemailaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.status": %w`, err)}
		}
	}
	return nil
}

func (_u *MicrosoftEmailAccountUpdateOne) sqlSave(ctx context.Context) (_node *MicrosoftEmailAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(microsoftemailaccount.Table, microsoftemailaccount.Columns, sqlgraph.NewFieldSpec(microsoftemailaccount.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MicrosoftEmailAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, microsoftemailaccount.FieldID)
		for _, f := range fields {
			if !microsoftemailaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != microsoftemailaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(microsoftemailaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(microsoftemailaccount.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(microsoftemailaccount.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(microsoftemailaccount.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(microsoftemailaccount.FieldRefreshToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(microsoftemailaccount.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastCheckAt(); ok {
		_spec.SetField(microsoftemailaccount.FieldLastCheckAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckAtCleared() {
		_spec.ClearField(microsoftemailaccount.FieldLastCheckAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastFetchAt(); ok {
		_spec.SetField(microsoftemailaccount.FieldLastFetchAt, field.TypeTime, value)
	}
	if _u.mutation.LastFetchAtCleared() {
		_spec.ClearField(microsoftemailaccount.FieldLastFetchAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(microsoftemailaccount.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(microsoftemailaccount.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(microsoftemailaccount.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(microsoftemailaccount.FieldNotes, field.TypeString)
	}
	_node = &MicrosoftEmailAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{microsoftemailaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
