// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/microsoftemailaccount"
)

// MicrosoftEmailAccountCreate is the builder for creating a MicrosoftEmailAccount entity.
type MicrosoftEmailAccountCreate struct {
	config
	mutation *MicrosoftEmailAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MicrosoftEmailAccountCreate) SetCreatedAt(v time.Time) *MicrosoftEmailAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MicrosoftEmailAccountCreate) SetNillableCreatedAt(v *time.Time) *MicrosoftEmailAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MicrosoftEmailAccountCreate) SetUpdatedAt(v time.Time) *MicrosoftEmailAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MicrosoftEmailAccountCreate) SetNillableUpdatedAt(v *time.Time) *MicrosoftEmailAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *MicrosoftEmailAccountCreate) SetEmail(v string) *MicrosoftEmailAccountCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPassword sets the "password" field.
func (_c *MicrosoftEmailAccountCreate) SetPassword(v string) *MicrosoftEmailAccountCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *MicrosoftEmailAccountCreate) SetClientID(v string) *MicrosoftEmailAccountCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetRefreshToken sets the "refresh_token" field.
func (_c *MicrosoftEmailAccountCreate) SetRefreshToken(v string) *MicrosoftEmailAccountCreate {
	_c.mutation.SetRefreshToken(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *MicrosoftEmailAccountCreate) SetStatus(v string) *MicrosoftEmailAccountCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MicrosoftEmailAccountCreate) SetNillableStatus(v *string) *MicrosoftEmailAccountCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetLastCheckAt sets the "last_check_at" field.
func (_c *MicrosoftEmailAccountCreate) SetLastCheckAt(v time.Time) *MicrosoftEmailAccountCreate {
	_c.mutation.SetLastCheckAt(v)
	return _c
}

// SetNillableLastCheckAt sets the "last_check_at" field if the given value is not nil.
func (_c *MicrosoftEmailAccountCreate) SetNillableLastCheckAt(v *time.Time) *MicrosoftEmailAccountCreate {
	if v != nil {
		_c.SetLastCheckAt(*v)
	}
	return _c
}

// SetLastFetchAt sets the "last_fetch_at" field.
func (_c *MicrosoftEmailAccountCreate) SetLastFetchAt(v time.Time) *MicrosoftEmailAccountCreate {
	_c.mutation.SetLastFetchAt(v)
	return _c
}

// SetNillableLastFetchAt sets the "last_fetch_at" field if the given value is not nil.
func (_c *MicrosoftEmailAccountCreate) SetNillableLastFetchAt(v *time.Time) *MicrosoftEmailAccountCreate {
	if v != nil {
		_c.SetLastFetchAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *MicrosoftEmailAccountCreate) SetLastError(v string) *MicrosoftEmailAccountCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *MicrosoftEmailAccountCreate) SetNillableLastError(v *string) *MicrosoftEmailAccountCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *MicrosoftEmailAccountCreate) SetNotes(v string) *MicrosoftEmailAccountCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *MicrosoftEmailAccountCreate) SetNillableNotes(v *string) *MicrosoftEmailAccountCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// Mutation returns the MicrosoftEmailAccountMutation object of the builder.
func (_c *MicrosoftEmailAccountCreate) Mutation() *MicrosoftEmailAccountMutation {
	return _c.mutation
}

// Save creates the MicrosoftEmailAccount in the database.
func (_c *MicrosoftEmailAccountCreate) Save(ctx context.Context) (*MicrosoftEmailAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MicrosoftEmailAccountCreate) SaveX(ctx context.Context) *MicrosoftEmailAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MicrosoftEmailAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MicrosoftEmailAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MicrosoftEmailAccountCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := microsoftemailaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := microsoftemailaccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := microsoftemailaccount.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MicrosoftEmailAccountCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MicrosoftEmailAccount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MicrosoftEmailAccount.updated_at"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "MicrosoftEmailAccount.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := microsoftemailaccount.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "MicrosoftEmailAccount.password"`)}
	}
	if v, ok := _c.mutation.Password(); ok {
		if err := microsoftemailaccount.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.password": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "MicrosoftEmailAccount.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := microsoftemailaccount.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RefreshToken(); !ok {
		return &ValidationError{Name: "refresh_token", err: errors.New(`ent: missing required field "MicrosoftEmailAccount.refresh_token"`)}
	}
	if v, ok := _c.mutation.RefreshToken(); ok {
		if err := microsoftemailaccount.RefreshTokenValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.refresh_token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "MicrosoftEmailAccount.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := microsoftemailaccount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MicrosoftEmailAccount.status": %w`, err)}
		}
	}
	return nil
}

func (_c *MicrosoftEmailAccountCreate) sqlSave(ctx context.Context) (*MicrosoftEmailAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MicrosoftEmailAccountCreate) createSpec() (*MicrosoftEmailAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &MicrosoftEmailAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(microsoftemailaccount.Table, sqlgraph.NewFieldSpec(microsoftemailaccount.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(microsoftemailaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(microsoftemailaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(microsoftemailaccount.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(microsoftemailaccount.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(microsoftemailaccount.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.RefreshToken(); ok {
		_spec.SetField(microsoftemailaccount.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(microsoftemailaccount.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.LastCheckAt(); ok {
		_spec.SetField(microsoftemailaccount.FieldLastCheckAt, field.TypeTime, value)
		_node.LastCheckAt = &value
	}
	if value, ok := _c.mutation.LastFetchAt(); ok {
		_spec.SetField(microsoftemailaccount.FieldLastFetchAt, field.TypeTime, value)
		_node.LastFetchAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(microsoftemailaccount.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(microsoftemailaccount.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MicrosoftEmailAccount.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MicrosoftEmailAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MicrosoftEmailAccountCreate) OnConflict(opts ...sql.ConflictOption) *MicrosoftEmailAccountUpsertOne {
	_c.conflict = opts
	return &MicrosoftEmailAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MicrosoftEmailAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MicrosoftEmailAccountCreate) OnConflictColumns(columns ...string) *MicrosoftEmailAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MicrosoftEmailAccountUpsertOne{
		create: _c,
	}
}

type (
	// MicrosoftEmailAccountUpsertOne is the builder for "upsert"-ing
	//  one MicrosoftEmailAccount node.
	MicrosoftEmailAccountUpsertOne struct {
		create *MicrosoftEmailAccountCreate
	}

	// MicrosoftEmailAccountUpsert is the "OnConflict" setter.
	MicrosoftEmailAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MicrosoftEmailAccountUpsert) SetUpdatedAt(v time.Time) *MicrosoftEmailAccountUpsert {
	u.Set(microsoftemailaccount.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsert) UpdateUpdatedAt() *MicrosoftEmailAccountUpsert {
	u.SetExcluded(microsoftemailaccount.FieldUpdatedAt)
	return u
}

// SetEmail sets the "email" field.
func (u *MicrosoftEmailAccountUpsert) SetEmail(v string) *MicrosoftEmailAccountUpsert {
	u.Set(microsoftemailaccount.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsert) UpdateEmail() *MicrosoftEmailAccountUpsert {
	u.SetExcluded(microsoftemailaccount.FieldEmail)
	return u
}

// SetPassword sets the "password" field.
func (u *MicrosoftEmailAccountUpsert) SetPassword(v string) *MicrosoftEmailAccountUpsert {
	u.Set(microsoftemailaccount.FieldPassword, v)
	return u
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsert) UpdatePassword() *MicrosoftEmailAccountUpsert {
	u.SetExcluded(microsoftemailaccount.FieldPassword)
	return u
}

// SetClientID sets the "client_id" field.
func (u *MicrosoftEmailAccountUpsert) SetClientID(v string) *MicrosoftEmailAccountUpsert {
	u.Set(microsoftemailaccount.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsert) UpdateClientID() *MicrosoftEmailAccountUpsert {
	u.SetExcluded(microsoftemailaccount.FieldClientID)
	return u
}

// SetRefreshToken sets the "refresh_token" field.
func (u *MicrosoftEmailAccountUpsert) SetRefreshToken(v string) *MicrosoftEmailAccountUpsert {
	u.Set(microsoftemailaccount.FieldRefreshToken, v)
	return u
}

// UpdateRefreshToken sets the "refresh_token" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsert) UpdateRefreshToken() *MicrosoftEmailAccountUpsert {
	u.SetExcluded(microsoftemailaccount.FieldRefreshToken)
	return u
}

// SetStatus sets the "status" field.
func (u *MicrosoftEmailAccountUpsert) SetStatus(v string) *MicrosoftEmailAccountUpsert {
	u.Set(microsoftemailaccount.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsert) UpdateStatus() *MicrosoftEmailAccountUpsert {
	u.SetExcluded(microsoftemailaccount.FieldStatus)
	return u
}

// SetLastCheckAt sets the "last_check_at" field.
func (u *MicrosoftEmailAccountUpsert) SetLastCheckAt(v time.Time) *MicrosoftEmailAccountUpsert {
	u.Set(microsoftemailaccount.FieldLastCheckAt, v)
	return u
}

// UpdateLastCheckAt sets the "last_check_at" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsert) UpdateLastCheckAt() *MicrosoftEmailAccountUpsert {
	u.SetExcluded(microsoftemailaccount.FieldLastCheckAt)
	return u
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (u *MicrosoftEmailAccountUpsert) ClearLastCheckAt() *MicrosoftEmailAccountUpsert {
	u.SetNull(microsoftemailaccount.FieldLastCheckAt)
	return u
}

// SetLastFetchAt sets the "last_fetch_at" field.
func (u *MicrosoftEmailAccountUpsert) SetLastFetchAt(v time.Time) *MicrosoftEmailAccountUpsert {
	u.Set(microsoftemailaccount.FieldLastFetchAt, v)
	return u
}

// UpdateLastFetchAt sets the "last_fetch_at" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsert) UpdateLastFetchAt() *MicrosoftEmailAccountUpsert {
	u.SetExcluded(microsoftemailaccount.FieldLastFetchAt)
	return u
}

// ClearLastFetchAt clears the value of the "last_fetch_at" field.
func (u *MicrosoftEmailAccountUpsert) ClearLastFetchAt() *MicrosoftEmailAccountUpsert {
	u.SetNull(microsoftemailaccount.FieldLastFetchAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *MicrosoftEmailAccountUpsert) SetLastError(v string) *MicrosoftEmailAccountUpsert {
	u.Set(microsoftemailaccount.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsert) UpdateLastError() *MicrosoftEmailAccountUpsert {
	u.SetExcluded(microsoftemailaccount.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *MicrosoftEmailAccountUpsert) ClearLastError() *MicrosoftEmailAccountUpsert {
	u.SetNull(microsoftemailaccount.FieldLastError)
	return u
}

// SetNotes sets the "notes" field.
func (u *MicrosoftEmailAccountUpsert) SetNotes(v string) *MicrosoftEmailAccountUpsert {
	u.Set(microsoftemailaccount.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsert) UpdateNotes() *MicrosoftEmailAccountUpsert {
	u.SetExcluded(microsoftemailaccount.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *MicrosoftEmailAccountUpsert) ClearNotes() *MicrosoftEmailAccountUpsert {
	u.SetNull(microsoftemailaccount.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MicrosoftEmailAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MicrosoftEmailAccountUpsertOne) UpdateNewValues() *MicrosoftEmailAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(microsoftemailaccount.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MicrosoftEmailAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MicrosoftEmailAccountUpsertOne) Ignore() *MicrosoftEmailAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MicrosoftEmailAccountUpsertOne) DoNothing() *MicrosoftEmailAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MicrosoftEmailAccountCreate.OnConflict
// documentation for more info.
func (u *MicrosoftEmailAccountUpsertOne) Update(set func(*MicrosoftEmailAccountUpsert)) *MicrosoftEmailAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MicrosoftEmailAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MicrosoftEmailAccountUpsertOne) SetUpdatedAt(v time.Time) *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertOne) UpdateUpdatedAt() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEmail sets the "email" field.
func (u *MicrosoftEmailAccountUpsertOne) SetEmail(v string) *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertOne) UpdateEmail() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateEmail()
	})
}

// SetPassword sets the "password" field.
func (u *MicrosoftEmailAccountUpsertOne) SetPassword(v string) *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertOne) UpdatePassword() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdatePassword()
	})
}

// SetClientID sets the "client_id" field.
func (u *MicrosoftEmailAccountUpsertOne) SetClientID(v string) *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertOne) UpdateClientID() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateClientID()
	})
}

// SetRefreshToken sets the "refresh_token" field.
func (u *MicrosoftEmailAccountUpsertOne) SetRefreshToken(v string) *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetRefreshToken(v)
	})
}

// UpdateRefreshToken sets the "refresh_token" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertOne) UpdateRefreshToken() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateRefreshToken()
	})
}

// SetStatus sets the "status" field.
func (u *MicrosoftEmailAccountUpsertOne) SetStatus(v string) *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertOne) UpdateStatus() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateStatus()
	})
}

// SetLastCheckAt sets the "last_check_at" field.
func (u *MicrosoftEmailAccountUpsertOne) SetLastCheckAt(v time.Time) *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetLastCheckAt(v)
	})
}

// UpdateLastCheckAt sets the "last_check_at" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertOne) UpdateLastCheckAt() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateLastCheckAt()
	})
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (u *MicrosoftEmailAccountUpsertOne) ClearLastCheckAt() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.ClearLastCheckAt()
	})
}

// SetLastFetchAt sets the "last_fetch_at" field.
func (u *MicrosoftEmailAccountUpsertOne) SetLastFetchAt(v time.Time) *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetLastFetchAt(v)
	})
}

// UpdateLastFetchAt sets the "last_fetch_at" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertOne) UpdateLastFetchAt() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateLastFetchAt()
	})
}

// ClearLastFetchAt clears the value of the "last_fetch_at" field.
func (u *MicrosoftEmailAccountUpsertOne) ClearLastFetchAt() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.ClearLastFetchAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *MicrosoftEmailAccountUpsertOne) SetLastError(v string) *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertOne) UpdateLastError() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *MicrosoftEmailAccountUpsertOne) ClearLastError() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.ClearLastError()
	})
}

// SetNotes sets the "notes" field.
func (u *MicrosoftEmailAccountUpsertOne) SetNotes(v string) *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertOne) UpdateNotes() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *MicrosoftEmailAccountUpsertOne) ClearNotes() *MicrosoftEmailAccountUpsertOne {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *MicrosoftEmailAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MicrosoftEmailAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MicrosoftEmailAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MicrosoftEmailAccountUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MicrosoftEmailAccountUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MicrosoftEmailAccountCreateBulk is the builder for creating many MicrosoftEmailAccount entities in bulk.
type MicrosoftEmailAccountCreateBulk struct {
	config
	err      error
	builders []*MicrosoftEmailAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the MicrosoftEmailAccount entities in the database.
func (_c *MicrosoftEmailAccountCreateBulk) Save(ctx context.Context) ([]*MicrosoftEmailAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MicrosoftEmailAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MicrosoftEmailAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MicrosoftEmailAccountCreateBulk) SaveX(ctx context.Context) []*MicrosoftEmailAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MicrosoftEmailAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MicrosoftEmailAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MicrosoftEmailAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MicrosoftEmailAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MicrosoftEmailAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *MicrosoftEmailAccountUpsertBulk {
	_c.conflict = opts
	return &MicrosoftEmailAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MicrosoftEmailAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MicrosoftEmailAccountCreateBulk) OnConflictColumns(columns ...string) *MicrosoftEmailAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MicrosoftEmailAccountUpsertBulk{
		create: _c,
	}
}

// MicrosoftEmailAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of MicrosoftEmailAccount nodes.
type MicrosoftEmailAccountUpsertBulk struct {
	create *MicrosoftEmailAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MicrosoftEmailAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MicrosoftEmailAccountUpsertBulk) UpdateNewValues() *MicrosoftEmailAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(microsoftemailaccount.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MicrosoftEmailAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MicrosoftEmailAccountUpsertBulk) Ignore() *MicrosoftEmailAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MicrosoftEmailAccountUpsertBulk) DoNothing() *MicrosoftEmailAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MicrosoftEmailAccountCreateBulk.OnConflict
// documentation for more info.
func (u *MicrosoftEmailAccountUpsertBulk) Update(set func(*MicrosoftEmailAccountUpsert)) *MicrosoftEmailAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MicrosoftEmailAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MicrosoftEmailAccountUpsertBulk) SetUpdatedAt(v time.Time) *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertBulk) UpdateUpdatedAt() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEmail sets the "email" field.
func (u *MicrosoftEmailAccountUpsertBulk) SetEmail(v string) *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertBulk) UpdateEmail() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateEmail()
	})
}

// SetPassword sets the "password" field.
func (u *MicrosoftEmailAccountUpsertBulk) SetPassword(v string) *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertBulk) UpdatePassword() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdatePassword()
	})
}

// SetClientID sets the "client_id" field.
func (u *MicrosoftEmailAccountUpsertBulk) SetClientID(v string) *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertBulk) UpdateClientID() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateClientID()
	})
}

// SetRefreshToken sets the "refresh_token" field.
func (u *MicrosoftEmailAccountUpsertBulk) SetRefreshToken(v string) *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetRefreshToken(v)
	})
}

// UpdateRefreshToken sets the "refresh_token" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertBulk) UpdateRefreshToken() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateRefreshToken()
	})
}

// SetStatus sets the "status" field.
func (u *MicrosoftEmailAccountUpsertBulk) SetStatus(v string) *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertBulk) UpdateStatus() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateStatus()
	})
}

// SetLastCheckAt sets the "last_check_at" field.
func (u *MicrosoftEmailAccountUpsertBulk) SetLastCheckAt(v time.Time) *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetLastCheckAt(v)
	})
}

// UpdateLastCheckAt sets the "last_check_at" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertBulk) UpdateLastCheckAt() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateLastCheckAt()
	})
}

// ClearLastCheckAt clears the value of the "last_check_at" field.
func (u *MicrosoftEmailAccountUpsertBulk) ClearLastCheckAt() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.ClearLastCheckAt()
	})
}

// SetLastFetchAt sets the "last_fetch_at" field.
func (u *MicrosoftEmailAccountUpsertBulk) SetLastFetchAt(v time.Time) *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetLastFetchAt(v)
	})
}

// UpdateLastFetchAt sets the "last_fetch_at" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertBulk) UpdateLastFetchAt() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateLastFetchAt()
	})
}

// ClearLastFetchAt clears the value of the "last_fetch_at" field.
func (u *MicrosoftEmailAccountUpsertBulk) ClearLastFetchAt() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.ClearLastFetchAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *MicrosoftEmailAccountUpsertBulk) SetLastError(v string) *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertBulk) UpdateLastError() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *MicrosoftEmailAccountUpsertBulk) ClearLastError() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.ClearLastError()
	})
}

// SetNotes sets the "notes" field.
func (u *MicrosoftEmailAccountUpsertBulk) SetNotes(v string) *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *MicrosoftEmailAccountUpsertBulk) UpdateNotes() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *MicrosoftEmailAccountUpsertBulk) ClearNotes() *MicrosoftEmailAccountUpsertBulk {
	return u.Update(func(s *MicrosoftEmailAccountUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *MicrosoftEmailAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MicrosoftEmailAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MicrosoftEmailAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MicrosoftEmailAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
