// Code generated by ent, DO NOT EDIT.

package microsoftemailaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldEmail, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldPassword, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldClientID, v))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldRefreshToken, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldStatus, v))
}

// LastCheckAt applies equality check predicate on the "last_check_at" field. It's identical to LastCheckAtEQ.
func LastCheckAt(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldLastCheckAt, v))
}

// LastFetchAt applies equality check predicate on the "last_fetch_at" field. It's identical to LastFetchAtEQ.
func LastFetchAt(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldLastFetchAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldLastError, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContainsFold(FieldPassword, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContainsFold(FieldClientID, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenContains applies the Contains predicate on the "refresh_token" field.
func RefreshTokenContains(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContains(FieldRefreshToken, v))
}

// RefreshTokenHasPrefix applies the HasPrefix predicate on the "refresh_token" field.
func RefreshTokenHasPrefix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasPrefix(FieldRefreshToken, v))
}

// RefreshTokenHasSuffix applies the HasSuffix predicate on the "refresh_token" field.
func RefreshTokenHasSuffix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasSuffix(FieldRefreshToken, v))
}

// RefreshTokenEqualFold applies the EqualFold predicate on the "refresh_token" field.
func RefreshTokenEqualFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEqualFold(FieldRefreshToken, v))
}

// RefreshTokenContainsFold applies the ContainsFold predicate on the "refresh_token" field.
func RefreshTokenContainsFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContainsFold(FieldRefreshToken, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContainsFold(FieldStatus, v))
}

// LastCheckAtEQ applies the EQ predicate on the "last_check_at" field.
func LastCheckAtEQ(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldLastCheckAt, v))
}

// LastCheckAtNEQ applies the NEQ predicate on the "last_check_at" field.
func LastCheckAtNEQ(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNEQ(FieldLastCheckAt, v))
}

// LastCheckAtIn applies the In predicate on the "last_check_at" field.
func LastCheckAtIn(vs ...time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIn(FieldLastCheckAt, vs...))
}

// LastCheckAtNotIn applies the NotIn predicate on the "last_check_at" field.
func LastCheckAtNotIn(vs ...time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotIn(FieldLastCheckAt, vs...))
}

// LastCheckAtGT applies the GT predicate on the "last_check_at" field.
func LastCheckAtGT(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGT(FieldLastCheckAt, v))
}

// LastCheckAtGTE applies the GTE predicate on the "last_check_at" field.
func LastCheckAtGTE(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGTE(FieldLastCheckAt, v))
}

// LastCheckAtLT applies the LT predicate on the "last_check_at" field.
func LastCheckAtLT(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLT(FieldLastCheckAt, v))
}

// LastCheckAtLTE applies the LTE predicate on the "last_check_at" field.
func LastCheckAtLTE(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLTE(FieldLastCheckAt, v))
}

// LastCheckAtIsNil applies the IsNil predicate on the "last_check_at" field.
func LastCheckAtIsNil() predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIsNull(FieldLastCheckAt))
}

// LastCheckAtNotNil applies the NotNil predicate on the "last_check_at" field.
func LastCheckAtNotNil() predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotNull(FieldLastCheckAt))
}

// LastFetchAtEQ applies the EQ predicate on the "last_fetch_at" field.
func LastFetchAtEQ(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldLastFetchAt, v))
}

// LastFetchAtNEQ applies the NEQ predicate on the "last_fetch_at" field.
func LastFetchAtNEQ(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNEQ(FieldLastFetchAt, v))
}

// LastFetchAtIn applies the In predicate on the "last_fetch_at" field.
func LastFetchAtIn(vs ...time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIn(FieldLastFetchAt, vs...))
}

// LastFetchAtNotIn applies the NotIn predicate on the "last_fetch_at" field.
func LastFetchAtNotIn(vs ...time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotIn(FieldLastFetchAt, vs...))
}

// LastFetchAtGT applies the GT predicate on the "last_fetch_at" field.
func LastFetchAtGT(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGT(FieldLastFetchAt, v))
}

// LastFetchAtGTE applies the GTE predicate on the "last_fetch_at" field.
func LastFetchAtGTE(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGTE(FieldLastFetchAt, v))
}

// LastFetchAtLT applies the LT predicate on the "last_fetch_at" field.
func LastFetchAtLT(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLT(FieldLastFetchAt, v))
}

// LastFetchAtLTE applies the LTE predicate on the "last_fetch_at" field.
func LastFetchAtLTE(v time.Time) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLTE(FieldLastFetchAt, v))
}

// LastFetchAtIsNil applies the IsNil predicate on the "last_fetch_at" field.
func LastFetchAtIsNil() predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIsNull(FieldLastFetchAt))
}

// LastFetchAtNotNil applies the NotNil predicate on the "last_fetch_at" field.
func LastFetchAtNotNil() predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotNull(FieldLastFetchAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContainsFold(FieldLastError, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.FieldContainsFold(FieldNotes, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MicrosoftEmailAccount) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MicrosoftEmailAccount) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MicrosoftEmailAccount) predicate.MicrosoftEmailAccount {
	return predicate.MicrosoftEmailAccount(sql.NotPredicates(p))
}
